### ISSUE TITLE
TODO Finale

### ISSUE THREAD

**Issue by Ayfri** [Galileo-Bot/Rocket-Pub-Manager#18]
- [x] Ajouter tous les types de sanctions
- [x] Automatiquement envoyer les sanctions dans le salon de logs.
- [x] Ajouter un message à la fin de tous les salons de pub.
- [x] Détecter les sanctions manuelles, les envoyer et les enregistrer.
- [x] Ajouter des sanctions sur les messages directement avec les messages commands.
- [x] Ajouter les commandes de warns de publicités directes, avec peut-être un menu Discord ?
- [x] Passer les commandes via réactions en boutons discord.

Débug requis avant de faire cette liste :
- [ ] Passer les sanctions en complètement automatiques.
- [ ] Automatiquement sanctionner les personnes suivant le nombre de sanctions.

Peut être :
- [ ] Ajout d'une blacklist de personnes/pubs/messages.
